name: te-classification
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - intel-openmp=2025.0.0
  - joblib=1.5.2
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - networkx=3.5
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.7.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==25.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyg-lib==0.5.0+pt26cu124
      - pyparsing==3.2.5
      - pyyaml==6.0.3
      - requests==2.32.5
      - sentry-sdk==2.45.0
      - smmap==5.0.2
      - sympy==1.13.1
      - torch==2.6.0+cu124
      - torch-cluster==1.6.3+pt26cu124
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt26cu124
      - torch-sparse==0.6.18+pt26cu124
      - torch-spline-conv==1.2.2+pt26cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - wandb==0.23.0
      - xxhash==3.6.0
      - yarl==1.22.0
