name: te-classification
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - yaml
  - networkx
  - scikit-learn
  - tqdm
  - pip:
    - aiohappyeyeballs
    - aiohttp
    - aiosignal
    - annotated-types
    - attrs
    - certifi
    - charset-normalizer
    - click
    - filelock
    - frozenlist
    - fsspec
    - gitdb
    - GitPython
    - idna
    - Jinja2
    - MarkupSafe
    - mpmath
    - multidict
    - packaging
    - pillow
    - platformdirs
    - propcache
    - protobuf
    - psutil
    - pydantic
    - pydantic_core
    - pyg_lib
    - pyparsing
    - PyYAML
    - requests
    - sentry-sdk
    - setuptools
    - smmap
    - sympy
    - torch
    - torch-geometric
    - torch_cluster
    - torch_scatter
    - torch_sparse
    - torch_spline_conv
    - torchaudio
    - torchvision
    - typing-inspection
    - typing_extensions
    - urllib3
    - wandb
    - wheel
    - xxhash
    - yarl 

